xsd2php:
  namespaces:
    'urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100': 'horstoeko\zugferd\entities\basicwl\rsm'
    'urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100': 'horstoeko\zugferd\entities\basicwl\ram'
    'urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100': 'horstoeko\zugferd\entities\basicwl\udt'
    'urn:un:unece:uncefact:data:standard:QualifiedDataType:100': 'horstoeko\zugferd\entities\basicwl\qdt'
  destinations_php: 
    'horstoeko\zugferd\entities\basicwl\rsm': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/entities/basicwl/rsm'
    'horstoeko\zugferd\entities\basicwl\ram': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/entities/basicwl/ram'
    'horstoeko\zugferd\entities\basicwl\udt': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/entities/basicwl/udt'
    'horstoeko\zugferd\entities\basicwl\qdt': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/entities/basicwl/qdt'
  destinations_jms: 
    'horstoeko\zugferd\entities\basicwl\rsm': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/yaml/basicwl/rsm'
    'horstoeko\zugferd\entities\basicwl\ram': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/yaml/basicwl/ram'
    'horstoeko\zugferd\entities\basicwl\udt': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/yaml/basicwl/udt'
    'horstoeko\zugferd\entities\basicwl\qdt': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/yaml/basicwl/qdt'
  destinations_validation:
    'horstoeko\zugferd\entities\basicwl\rsm': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/validation/basicwl/rsm'
    'horstoeko\zugferd\entities\basicwl\ram': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/validation/basicwl/ram'
    'horstoeko\zugferd\entities\basicwl\udt': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/validation/basicwl/udt'
    'horstoeko\zugferd\entities\basicwl\qdt': '/srv/www/dev/local-horstoeko-zugferd/vendor/horstoeko/zugferd/src/validation/basicwl/qdt'
  configs_jms:
    xml_cdata: false
  aliases:
    'http://www.w3.org/2001/XMLSchema':
      anyType: 'string'
      anySimpleType: 'string'
